site_name: LLM as a Judge
site_description: A comprehensive framework for evaluating documents using Large Language Models
site_url: https://takuyakubo.github.io/llm-as-a-judge

repo_name: takuyakubo/llm-as-a-judge
repo_url: https://github.com/takuyakubo/llm-as-a-judge

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - mkdocs-jupyter:
      execute: false
      include_source: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - First Evaluation: first-evaluation.md
  - User Guide:
    - Basic Usage: usage/basic.md
    - Creating Rubrics: usage/rubrics.md
    - Multiple Providers: usage/providers.md
    - CLI Reference: usage/cli.md
  - Advanced:
    - Custom Criteria: advanced/custom-criteria.md
    - Batch Evaluation: advanced/batch.md
    - Integration: advanced/integration.md
  - API Reference:
    - Core Classes: api/core.md
    - Evaluator: api/evaluator.md
    - Providers: api/providers.md
    - CLI: api/cli.md
  - Examples:
    - Jupyter Notebooks: examples/notebooks.md
    - Use Cases: examples/use-cases.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/takuyakubo/llm-as-a-judge